spring:
  datasource:
    url: jdbc:mysql://localhost:3306/otpdb
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # mail_service
  mail:
    host: smtp.gmail.com
    port: 587
    username: mlkrahil9@gmail.com
    password: hxbqjnqqqstwwiug
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
