spring:
  datasource:
    url: jdbc:mysql://localhost:3306/busReservation
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB   # Maximum size of the file that can be uploaded
      max-request-size: 10MB   # Maximum size of the request that can be handled
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true # Set it to true if you want to see SQL queries in the console
        format_sql: true # Set it to true if you want to format SQL queries
  mail:
    host: smtp.gmail.com         # SMTP server host
    port: 587                      # SMTP server port
    username: rahil02397@gmail.com       # SMTP server username
    password: dcdamsvgodxnrdma       # SMTP server password
    properties:
      mail:
        smtp:
          auth: true               # Enable SMTP authentication
          starttls:
            enable: true           # Enable STARTTLS for secure connection


